### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by remy727** [heroku/heroku-accounts#48]
```bash
$ heroku plugins:install @heroku-cli/heroku-accounts --verbose
Installing plugin @heroku-cli/heroku-accounts...
/home/remy727/.local/share/heroku: /home/remy727/.local/share/heroku/client/9.3.0-65eb66a/node_modules/yarn/bin/yarn.js add @heroku-cli/heroku-accounts@latest 
Installing plugin @heroku-cli/heroku-accounts... ⣾
yarn add v1.22.19
verbose 0.158670669 Checking for configuration file "/home/remy727/.local/share/heroku/.npmrc".
verbose 0.159171228 Checking for configuration file "/home/remy727/.npmrc".
verbose 0.159369023 Checking for configuration file "/home/remy727/.local/share/heroku/client/9.3.0-65eb66a/etc/npmrc".
verbose 0.159613696 Checking for configuration file "/home/remy727/.local/share/heroku/.npmrc".
verbose 0.160640864 Checking for configuration file "/home/remy727/.local/share/.npmrc".
verbose 0.160818122 Checking for configuration file "/home/remy727/.local/.npmrc".
verbose 0.161089512 Checking for configuration file "/home/remy727/.npmrc".
verbose 0.161304275 Checking for configuration file "/home/.npmrc".
verbose 0.162088525 Checking for configuration file "/home/remy727/.local/share/heroku/.yarnrc".
verbose 0.162371232 Checking for configuration file "/home/remy727/.yarnrc".
verbose 0.162654287 Found configuration file "/home/remy727/.yarnrc".
verbose 0.163070701 Checking for configuration file "/home/remy727/.local/share/heroku/client/9.3.0-65eb66a/etc/yarnrc".
verbose 0.163516137 Checking for configuration file "/home/remy727/.local/share/heroku/.yarnrc".
verbose 0.163699463 Checking for configuration file "/home/remy727/.local/share/.yarnrc".
verbose 0.164006636 Checking for configuration file "/home/remy727/.local/.yarnrc".
verbose 0.164634521 Checking for configuration file "/home/remy727/.yarnrc".
verbose 0.165197065 Found configuration file "/home/remy727/.yarnrc".
verbose 0.16565544 Checking for configuration file "/home/.yarnrc".
Installing plugin @heroku-cli/heroku-accounts... ⣽
[1/4] Resolving packages...
Installing plugin @heroku-cli/heroku-accounts... ⣻
verbose 1.987197547 Request "https://registry.npmjs.org/@heroku-cli%2fheroku-accounts" finished with status code 404.
verbose 2.002032277 Error: https://registry.npmjs.org/@heroku-cli%2fheroku-accounts: Not found
    at Request.params.callback [as _callback] (/home/remy727/.local/share/heroku/client/9.3.0-65eb66a/node_modules/yarn/lib/cli.js:66145:18)
    at Request.self.callback (/home/remy727/.local/share/heroku/client/9.3.0-65eb66a/node_modules/yarn/lib/cli.js:140890:22)
    at Request.emit (node:events:513:28)
    at Request.<anonymous> (/home/remy727/.local/share/heroku/client/9.3.0-65eb66a/node_modules/yarn/lib/cli.js:141862:10)
    at Request.emit (node:events:513:28)
    at IncomingMessage.<anonymous> (/home/remy727/.local/share/heroku/client/9.3.0-65eb66a/node_modules/yarn/lib/cli.js:141784:12)
    at Object.onceWrapper (node:events:627:28)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
Installing plugin @heroku-cli/heroku-accounts... ⢿
error An unexpected error occurred: "https://registry.npmjs.org/@heroku-cli%2fheroku-accounts: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/home/remy727/.local/share/heroku/yarn-error.log".
Installing plugin @heroku-cli/heroku-accounts... failed
    Error: yarn add @heroku-cli/heroku-accounts@latest --non-interactive --mutex=file:/home/remy727/.local/share/heroku/yarn.lock 
    --preferred-cache-folder=/home/remy727/.cache/heroku/yarn --check-files --verbose --registry=https://registry.npmjs.org exited with code 1
```

**Comment by remy727** [comment]
I installed `heroku-accounts` package globally and tried installing `@heroku-cli/heroku-accounts` plugin. It worked.

### Step 1
```bash
$ npm i -g heroku-accounts
```

### Step 2
```bash
$ heroku plugins:install @heroku-cli/heroku-accounts
```
